### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by zagwalker** [rene00/gspread-import-csv#1]
Hi Rene,

When running:
`python gspread_import_csv.py --config-file=gspread_import_csv.conf --csv-file=filename.csv --document-title="Filename_Auto"`

Getting:
```
Traceback (most recent call last):
  File "gspread_import_csv.py", line 108, in <module>
    sys.exit(main())
  File "gspread_import_csv.py", line 70, in main
    google_docs_folder_id = google_config['google_docs_folder_id']
KeyError: 'google_docs_folder_id'
```

Any idea what it might be?

Thanks
Lev

**Comment by zagwalker** [comment]
Well, everything is even worse:
https://developers.google.com/identity/protocols/AuthForInstalledApps
